"""add riot reqeust table

Revision ID: 060ccd072103
Revises: 4bd5e2adf8a4
Create Date: 2024-06-15 01:00:00.207035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '060ccd072103'
down_revision: Union[str, None] = '4bd5e2adf8a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_key_usage',
    sa.Column('create_date', sa.DateTime(), nullable=False),
    sa.Column('api_key', sa.String(length=78), nullable=False),
    sa.Column('services', sa.String(length=255), nullable=False),
    sa.Column('last_update', sa.DateTime(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('api_key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('api_key_usage')
    # ### end Alembic commands ###
