"""fix_users_nullable_add_match_participants

Revision ID: 3327eaa8689f
Revises: dfeb37d84c35
Create Date: 2024-06-06 15:24:48.219384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3327eaa8689f'
down_revision: Union[str, None] = 'dfeb37d84c35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('create_timestamp', sa.DateTime(), nullable=False))
    op.add_column('matches', sa.Column('end_timestamp', sa.DateTime(), nullable=False))
    op.add_column('matches', sa.Column('game_name', sa.String(length=255), nullable=False))
    op.add_column('matches', sa.Column('game_type', sa.String(length=50), nullable=False))
    op.add_column('matches', sa.Column('map_id', sa.Integer(), nullable=False))
    op.add_column('matches', sa.Column('participants', sa.JSON(), nullable=False))
    op.create_index(op.f('ix_matches_create_timestamp'), 'matches', ['create_timestamp'], unique=False)
    op.create_index(op.f('ix_matches_game_mode'), 'matches', ['game_mode'], unique=False)
    op.alter_column('users', 'league_id',
               existing_type=sa.VARCHAR(length=78),
               nullable=True)
    op.alter_column('users', 'tier',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('users', 'rank',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('users', 'leaguePoints',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('users', 'win',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('users', 'losses',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('users', 'veteran',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'incative',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'fresh_blood',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'hot_streak',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'sommoner_id', new_column_name='summoner_id')
    op.drop_index('ix_users_sommoner_id', table_name='users')
    op.create_index(op.f('ix_users_summoner_id'), 'users', ['summoner_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'summoner_id', new_column_name='sommoner_id')
    op.drop_index(op.f('ix_users_summoner_id'), table_name='users')
    op.create_index('ix_users_sommoner_id', 'users', ['sommoner_id'], unique=False)
    op.alter_column('users', 'hot_streak',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'fresh_blood',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'incative',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'veteran',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'losses',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('users', 'win',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('users', 'leaguePoints',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('users', 'rank',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('users', 'tier',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('users', 'league_id',
               existing_type=sa.VARCHAR(length=78),
               nullable=False)
    op.drop_index(op.f('ix_matches_game_mode'), table_name='matches')
    op.drop_index(op.f('ix_matches_create_timestamp'), table_name='matches')
    op.drop_column('matches', 'participants')
    op.drop_column('matches', 'map_id')
    op.drop_column('matches', 'game_type')
    op.drop_column('matches', 'game_name')
    op.drop_column('matches', 'end_timestamp')
    op.drop_column('matches', 'create_timestamp')
    # ### end Alembic commands ###
