"""add requests task table

Revision ID: 4bd5e2adf8a4
Revises: 0d570799d126
Create Date: 2024-06-13 16:47:28.780639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4bd5e2adf8a4'
down_revision: Union[str, None] = '0d570799d126'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('requests',
    sa.Column('create_date', sa.DateTime(), nullable=False),
    sa.Column('request_id', sa.String(length=78), nullable=False),
    sa.Column('services', sa.String(length=255), nullable=False),
    sa.Column('ip', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('is_task', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('request_id')
    )
    op.create_table('task',
    sa.Column('task_id', sa.String(length=78), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=False),
    sa.Column('request_id', sa.String(length=78), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('is_complete', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['requests.request_id'], ),
    sa.PrimaryKeyConstraint('task_id')
    )
    op.add_column('users', sa.Column('game_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('tag_line', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'tag_line')
    op.drop_column('users', 'game_name')
    op.drop_table('task')
    op.drop_table('requests')
    # ### end Alembic commands ###
