"""fix_leagues

Revision ID: a83bfc781081
Revises: ed921c9c5152
Create Date: 2024-06-08 23:09:16.970360

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a83bfc781081'
down_revision: Union[str, None] = 'ed921c9c5152'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_league',
    sa.Column('summoner_id', sa.String(length=78), nullable=False),
    sa.Column('league_id', sa.String(length=78), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['league.league_id'], ),
    sa.ForeignKeyConstraint(['summoner_id'], ['users.summoner_id'], ),
    sa.PrimaryKeyConstraint('summoner_id', 'league_id')
    )
    op.drop_constraint('league_summoner_id_fkey', 'league', type_='foreignkey')
    op.drop_column('league', 'summoner_id')
    op.create_index(op.f('ix_users_accountId'), 'users', ['accountId'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_accountId'), table_name='users')
    op.add_column('league', sa.Column('summoner_id', sa.VARCHAR(length=78), autoincrement=False, nullable=False))
    op.create_foreign_key('league_summoner_id_fkey', 'league', 'users', ['summoner_id'], ['summoner_id'])
    op.drop_table('user_league')
    # ### end Alembic commands ###
