"""match_table_init

Revision ID: dfeb37d84c35
Revises: 
Create Date: 2024-06-05 19:23:13.203245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfeb37d84c35'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matches',
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('start_timestamp', sa.DateTime(), nullable=False),
    sa.Column('game_mode', sa.String(length=50), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('game_version', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('match_id')
    )
    op.create_index(op.f('ix_matches_start_timestamp'), 'matches', ['start_timestamp'], unique=False)
    op.create_table('users',
    sa.Column('puuid', sa.String(length=78), nullable=False),
    sa.Column('sommoner_id', sa.String(length=78), nullable=False),
    sa.Column('league_id', sa.String(length=78), nullable=False),
    sa.Column('tier', sa.String(length=50), nullable=False),
    sa.Column('rank', sa.String(length=50), nullable=False),
    sa.Column('leaguePoints', sa.Integer(), nullable=False),
    sa.Column('win', sa.Integer(), nullable=False),
    sa.Column('losses', sa.Integer(), nullable=False),
    sa.Column('veteran', sa.Boolean(), nullable=False),
    sa.Column('incative', sa.Boolean(), nullable=False),
    sa.Column('fresh_blood', sa.Boolean(), nullable=False),
    sa.Column('hot_streak', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('puuid')
    )
    op.create_index(op.f('ix_users_league_id'), 'users', ['league_id'], unique=False)
    op.create_index(op.f('ix_users_sommoner_id'), 'users', ['sommoner_id'], unique=False)
    op.create_table('user_matches',
    sa.Column('user_id', sa.String(length=78), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.match_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.puuid'], ),
    sa.PrimaryKeyConstraint('user_id', 'match_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_matches')
    op.drop_index(op.f('ix_users_sommoner_id'), table_name='users')
    op.drop_index(op.f('ix_users_league_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_matches_start_timestamp'), table_name='matches')
    op.drop_table('matches')
    # ### end Alembic commands ###
