"""fix_users_add_leagues

Revision ID: ed921c9c5152
Revises: e27573dca4a1
Create Date: 2024-06-08 20:38:45.291038

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed921c9c5152'
down_revision: Union[str, None] = 'e27573dca4a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column('users', sa.Column('accountId', sa.String(length=78), nullable=True))
    op.add_column('users', sa.Column('profile_icon_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('revision_date', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('summoner_level', sa.Integer(), nullable=True))
    op.drop_index('ix_users_league_id', table_name='users')
    op.drop_index('ix_users_summoner_id', table_name='users')
    op.create_index(op.f('ix_users_summoner_id'), 'users', ['summoner_id'], unique=True)
    op.drop_column('users', 'incative')
    op.drop_column('users', 'leaguePoints')
    op.drop_column('users', 'veteran')
    op.drop_column('users', 'rank')
    op.drop_column('users', 'league_id')
    op.drop_column('users', 'losses')
    op.drop_column('users', 'fresh_blood')
    op.drop_column('users', 'hot_streak')
    op.drop_column('users', 'win')
    op.drop_column('users', 'tier')
    op.create_table('league',
    sa.Column('league_id', sa.String(length=78), nullable=False),
    sa.Column('queue_type', sa.String(length=50), nullable=False),
    sa.Column('tier', sa.String(length=50), nullable=True),
    sa.Column('rank', sa.String(length=50), nullable=True),
    sa.Column('league_points', sa.Integer(), nullable=True),
    sa.Column('wins', sa.Integer(), nullable=True),
    sa.Column('losses', sa.Integer(), nullable=True),
    sa.Column('veteran', sa.Boolean(), nullable=True),
    sa.Column('inactive', sa.Boolean(), nullable=True),
    sa.Column('fresh_blood', sa.Boolean(), nullable=True),
    sa.Column('hot_streak', sa.Boolean(), nullable=True),
    sa.Column('summoner_id', sa.String(length=78), nullable=False),
    sa.ForeignKeyConstraint(['summoner_id'], ['users.summoner_id'], ),
    sa.PrimaryKeyConstraint('league_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('tier', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('win', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('hot_streak', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('fresh_blood', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('losses', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('league_id', sa.VARCHAR(length=78), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('rank', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('veteran', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('leaguePoints', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('incative', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_users_accountId'), table_name='users')
    op.drop_index(op.f('ix_users_summoner_id'), table_name='users')
    op.create_index('ix_users_summoner_id', 'users', ['summoner_id'], unique=False)
    op.create_index('ix_users_league_id', 'users', ['league_id'], unique=False)
    op.drop_column('users', 'summoner_level')
    op.drop_column('users', 'revision_date')
    op.drop_column('users', 'profile_icon_id')
    op.drop_column('users', 'accountId')
    op.drop_table('league')
    # ### end Alembic commands ###
