FROM python:3.8

# 작업 디렉토리 설정
WORKDIR /app
RUN pip install poetry
COPY ./* /app/

RUN poetry config virtualenvs.create false && poetry install --no-dev --no-interaction --no-ansi

# 소스 코드를 복사합니다.
COPY . /app

# 컨테이너가 시작될 때 실행할 명령을 지정합니다.
CMD ["python", "main.py"]
